W-13104927-API-Designer-audit-logs-fa
mulesoft/docs-access-management pull request #291
Opened 2023-05-24 15:06 UTC by failup

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-05-24 15:16 UTC, sarathecoubian approved these changes, later dismissed

2023-05-24 15:24 UTC, lbauret commented on modules/ROOT/pages/audit-logging.adoc
> +* commitID
We won't be including this at the end since the operation was not released into production. Can we remove this one please?

2023-05-24 15:31 UTC, iamerico requested changes
LGTM

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
* orgID
* projectID
* userID
* branchName

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
* orgID
* projectID
* userID
* projectID

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +|Revert commit
This event was not added

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
orgID
projectID
userID
repositoryName

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
orgID
projectID
userID
projectID

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
orgID
projectID
userID
projectID

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
orgID
projectID
userID
branchName

2023-05-24 15:31 UTC, iamerico commented on modules/ROOT/pages/audit-logging.adoc
> +Properties:
orgID
projectID
userID
projectID

2023-05-24 15:52 UTC, iamerico approved these changes
LGTM

2023-05-24 16:21 UTC, lbauret approved these changes
LGTM!

2023-05-29 18:02 UTC, dmerlob approved these changes

2023-05-29 18:07 UTC, merged