W-16338506 Updates for UI changes
mulesoft/docs-access-management pull request #352
Opened 2024-08-13 23:10 UTC by valkyrie69

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-08-14 13:37 UTC, dlhforce requested changes

2024-08-14 13:37 UTC, dlhforce commented on modules/ROOT/pages/users.adoc
> +When deleting a user from the root organization, all of the user's permissions are removed, and the user becomes unattached. When deleting a user from a business group, all of the user's permissions
The distinctions between operations on the selected org/BG vs the root org must be a holdover from the legacy UI, because in the modern UI, there is no org/BG selector for the Users page. For example, there's no way to enable/disable users "in the selected organization or business group", but instead, the enable/disable controls happen at the root org/tenant level.

This effectively invalidates the entire middle sentence of the "Delete users" description. It also occurs to me that there's a lot of redundancy between this description and the "Manage Deleted Users" section below, so I'm not sure how much of that is worth reiterating here.

2024-08-14 13:37 UTC, dlhforce commented on modules/ROOT/pages/users.adoc
> +On the access management *Users* page, you can:
Thanks for eliminating the reference to the "checkbox next to a user" from the legacy UI. 😅 

Also, it _feels_ to me like "Access Management" should be title-cased, but looking at the rest of the document, it's unclear to me what the standard capitalization is supposed to be.

2024-08-14 13:37 UTC, dlhforce commented on modules/ROOT/pages/users.adoc
> +The user's Settings page is where you can edit the user's first and last name, email address, and exempt them from two-factor authentication.
```suggestion
The user's Settings page is where you can edit the user's first and last name, email address, and exempt them from multi-factor authentication. 
```

I think our standard term here is "multi-factor authentication" or "MFA" instead of "two-factor authentication"

2024-08-14 13:37 UTC, dlhforce commented on modules/ROOT/pages/users.adoc
> +. Click the *Settings* tab.
👍

2024-08-14 23:00 UTC, valkyrie69 commented on modules/ROOT/pages/users.adoc
> +On the access management *Users* page, you can:
@dlhforce I agree that it *should* be, but according to our official product naming, it's not a product and shouldn't be capitalized. It is, I am positive, inconsistent in the docs.

2024-08-14 23:00 UTC, valkyrie69 commented on modules/ROOT/pages/users.adoc
> +The user's Settings page is where you can edit the user's first and last name, email address, and exempt them from two-factor authentication.
Yes, thank you!

2024-08-15 17:05 UTC, dlhforce submitted a review, later dismissed

2024-08-15 17:14 UTC, glenn-rodgers-sf approved these changes, later dismissed

2024-08-15 17:14 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/users.adoc
> +*
```suggestion

```

Is this an extra bullet?

2024-08-15 17:14 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/users.adoc
> +. Click the More actions menu (...) in the row for the invitation to manage.
Is there UI that should be bold here?

2024-08-15 17:14 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/users.adoc
> +The user's Settings page is where you can edit the user's first and last name, email address, and exempt them from multi-factor authentication.
```suggestion
The user's *Settings* page is where you can edit the user's first and last name, email address, and exempt them from multi-factor authentication. 
```

Should this UI?

2024-08-15 17:25 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/users.adoc
> +. There are three ways to access the user's Settings page:
```suggestion
. There are three ways to access the user's *Settings* page:
```

2024-08-15 17:56 UTC, glenn-rodgers-sf approved these changes

2024-08-15 18:22 UTC, merged