Document the behavior when creating a new env using an existing env name
mulesoft/docs-access-management pull request #88
Opened 2020-09-01 09:50 UTC by lee3star

Describe an un-common behavior/feature when creating an environment when an existing environment name is used. In this case, instead of returning 400 or 409 as normal RESTful service does, the call/operation is successful with a new environment created. The new environment has a unique ID, but the name is not the name you entered, but a "-<n>" appended to it, the <n> is the incremental number. This is working as designed as per the conversation here: https://mulesoft.slack.com/archives/G7JFWLX54/p1598918390006400

2020-09-01 17:14 UTC, sarathecoubian commented on modules/ROOT/pages/environments.adoc
> +* If an existing name is used to create a new environment, the newly created evironment name will have a "-<n>" appended to it, where the <n> is an incremental number
```suggestion
* If create a new environment using the name of an existing environment, the newly created environment name has `-<n>` appended to it, where `<n>` is an incremental number.
```

2020-09-14 18:58 UTC, sarathecoubian requested changes, later dismissed

2020-09-14 18:58 UTC, sarathecoubian commented on modules/ROOT/pages/environments.adoc
> +* If an existing name is used to create a new environment, the newly created evironment name will have a "-<n>" appended to it, where the <n> is an incremental number
@lee3star Please implement this change, and I can approve and merge when ready.

2021-03-23 15:21 UTC, sarathecoubian commented on modules/ROOT/pages/environments.adoc
> +* Depending on your CloudHub subscription, you may have restrictions on the number and type of environments you can create.
```suggestion
* Depending on your CloudHub subscription, you might have restrictions on the number and type of environments you can create.
```

2021-03-23 15:26 UTC, dukesphere approved these changes, later dismissed
suggested change

2021-03-23 15:26 UTC, dukesphere commented on modules/ROOT/pages/environments.adoc
> +* If you create a new environment using the name of an existing environment, the newly created environment name has `-<n>` appended to it, where `<n>` is an incremental number.
```suggestion
* If you create a new environment using the name of an existing environment, `-<n>` is appended to the name of the new environment. `<n>` is an incremental number.
```

2021-03-23 15:29 UTC, dukesphere approved these changes

2021-03-23 15:30 UTC, merged