Caveat this only works for IdP-Initiated SSO
mulesoft/docs-access-management pull request #90
Opened 2020-09-10 05:35 UTC by lee3star

Caveat this only works for IdP-Initiated SSO, also if the SAMLResponse's from a HAR file, it should be URL decoded first before it can be used.

2020-09-10 16:15 UTC, sarathecoubian requested changes

2020-09-10 16:15 UTC, sarathecoubian commented on modules/ROOT/pages/saml-bearer-token.adoc
> ++
```suggestion
```

2020-09-10 16:15 UTC, sarathecoubian commented on modules/ROOT/pages/saml-bearer-token.adoc
> ++
```suggestion
```

2020-09-10 16:15 UTC, sarathecoubian commented on modules/ROOT/pages/saml-bearer-token.adoc
> +This method works for IdP-Initiated SSO only as SP-Initiated SSO does not support unsolicited assertions.
```suggestion
Obtaining an API bearer token using a SAML assertion works only for IdP-Initiated single sign-on. Service provider-initiated SSO does not support unsolicited assertions. 
```

2020-09-10 16:15 UTC, sarathecoubian commented on modules/ROOT/pages/saml-bearer-token.adoc
> +If the SAML response was received from a HAR file via a text editor, the string is URL encoded. Please use a URL decoder such as urldecoder.org to decode the string first and try again.
```suggestion
If the SAML response string is URL encoded, you must decode the string before running the `curl` command.
```

2021-01-05 17:43 UTC, emileeburkeVT approved these changes

2021-01-05 17:43 UTC, sarathecoubian approved these changes

2021-01-05 17:44 UTC, merged